pub const SHADOW_WORK: &[&str] = &[
    "1. If you met yourself for the first time, what would be your first impressions?",
    "2. How would your loved ones describe you? Are they accurate? Why or why not?",
    "3. What are your toxic traits? How do these traits affect others? How do they impact your daily life?",
    "4. Make a list of your positive traits and negative traits. What are some things you can do to strengthen your positive traits? How can you start healing your negative traits?",
    "5. Create an avatar for your shadow self. What are their traits and qualities? What do you want to say to your shadow self?",
    "6. Think of one or two traits that you dislike about yourself. Where do these traits come from? Were they learned? Are they defense mechanisms? Explore as many ideas as you can.",
    "7. What makes you jealous? Why? What does it tell you about your own needs? Are these things you can work towards or something you should let go of?",
    "8. What's a trait you see in other people that you wish you had? What are some ways you can cultivate this trait in yourself?",
    "9. Which personality traits in other people drive you nuts? Why? Do you see yourself in any of these behaviors?",
    "10. How do you handle stress?",
    "11. What is your relationship to drama? Do you like it? Involve yourself in it? Cause it? Avoid it? Explore this.",
    "12. Are there any negative emotions or traits that feel normal to you that you express every day? What are they? When did you adopt them?",
];

pub const KNOW_YOURSELF: &[&str] = &[
    "13. Do you feel misunderstood? What misconceptions do people have about you?",
    "14. What triggers you? Why? Where does it come from?",
    "15. What are the primary aspects of yourself you'd like to approve? Explain your choice. Has anyone told you to work on these things before?",
    "16. Do you find it easy to forgive yourself? Why or why not?",
    "17. Do you forgive other people easily? Why or why not?",
    "18. What are your core values? Why have you chosen them? How do you live your values daily?",
    "19. What are/were your caregivers' core values? Do yours align or differ? Why do you think that is?",
    "20. What version of yourself do you try to project to the world? Are you being authentic?",
    "21. Where do you derive your sense of self-worth from? Is this a healthy or unhealthy source?",
    "22. What are some ways you could be more patient with yourself?",
    "23. What lies have you or do you tell yourself? Talk about why.",
    "24. Do you have recurring dreams or nightmares? What happens in them? What do you think your subconscious mind is trying to communicate to you?",
    "25. What's something you're afraid of doing? What's scary about it? How can you overcome that fear?",
    "26. Which negative emotions do you try to avoid? Why is that? Have you always been this way?",
    "27. Do you ask for help? Why or why not?",
    "28. What keeps you up at night? Where does this worry come from? How long have these issues been troubling you?",
    "29. How do you act when you're angry? Is this similar or different to how the people in your childhood act when angry?",
    "30. Describe a time you self-sabotaged. What happened? Why do you think you did it?",
    "31. Do you accept compliments well? Why or why not? Are there any compliments you receive that you struggle to believe about yourself?",
    "32. Write an apology letter to yourself.",
    "33. Do you hold grudges? What's hard for you to let go? Why?",
    "34. Describe a time you felt self-conscious or unsafe. What triggered these feelings for you?",
    "35. What areas of your life do you feel ignored or disregarded?",
    "36. If you could change one thing about yourself, what would it be and why?",
    "37. What triggers envy in you? Where does that come from?",
    "38. Are you overly sensitive to constructive criticism? Or do you respond well? Why is that?",
    "39. Are you easily influenced by other people's opinions? Do you find it easy or difficult to assert your voice? Talk about why.",
];

pub const EXAMINNG_PAST: &[&str] = &[
    "40. Think about a relationship you had to leave. Why did you do it? Why was it the right choice for you?",
    "41. Describe a time you felt wronged as a child. What happened? How did you react? What did you learn from this experience? Has it affected your life as an adult?",
    "42.What did your caregivers value growing up? Do you share the same values? Why or why not?",
    "43. Write a letter to your past self.",
    "44. What's an early childhood memory that has stuck with you into adulthood? Why do you think that is?",
    "45. What were you like as a child? How have you changed?",
    "46. What's your worst childhood memory? How did your parents or guardians respond? Were you cared for? Were your needs met?",
    "47. Write about a time you experienced something that seemed negative but turned out to be a positive thing in the long run.",
    "48. What do you wish you could change about your childhood? Talk about why.",
    "49. Which memories bring you the most shame? What feelings do they provoke? What do you do when you start feeling these things?",
    "50. How has your past trauma affected you? How do you carry it in your everyday life?",
];

pub const RELATIONSHIPS: &[&str] = &[
    "51. What kind of relationships do you have with your parents/caregivers, siblings, or other close family members? Is it better, worse, or the same as when you were growing up? Why?",
    "52. Have you ever developed an obsessive or unhealthy relationship? Why do you think this happened?",
    "53. Do you struggle with commitment? What challenges have you faced in your dating life that you want to work on?",
    "54. Is there a person you can't seem to forgive in your life? Write them a letter. What do you want to say to them?",
    "55. Was there a time you opened yourself up to someone and felt rejected? What happened? How has that affected you?",
    "56. Do you allow yourself to be vulnerable in relationships? Why or why not?",
    "57. In what ways are you similar to your parents/guardians? How are you different?",
    "58. Is there anyone in your life who belittles you or downplays your emotions? How does that affect you?",
    "59. Who has the most influence over you? Do they know? Is it healthy?",
    "60. Have you ever been in a codependent relationship? What about your family members? Talk about your experience with codependency as well as thoughts or feelings that come up about it.",
    "61. Write a letter to someone who has really hurt you. Let it all out. (Feel free to creatively destroy the letter when you're done.)",
    "62. Which relationships in your life no longer serve you. List them out. How would it feel to be free of these relationships? Why aren't you?",
    "63. Think about a conflict you had with someone. How did it play out? Is there anything you wish you had done differently? What was your role in the conflict? Did you take responsibility?",
    "64. Who have you let down in the past? Why did you do it? Where do you stand with this person currently?",
    "65. What is your love language? How did you learn it?",
];